apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-timescale.fullname" . }}
  labels: {{- include "mcp-timescale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mcp
      name: mcp
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      name: metrics
  selector: {{- include "mcp-timescale.selectorLabels" . | nindent 4 }}
