apiVersion: v2
name: "{MCP-NAME}"
description: SHORT_DESC_PLACEHOLDER
type: application
version: 0.0.0
appVersion: "0.0.0"
kubeVersion: ">=1.27.0-0"
home: https://github.com/giantswarm/{MCP-NAME}
maintainers:
  - name: Giant Swarm
    url: https://giantswarm.io
annotations:
  # 'all' = customers can deploy; 'giantswarm' = internal only.
  io.giantswarm.application.audience: giantswarm
  # 'true' if Giant Swarm takes responsibility for this app where deployed.
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: team-PLACEHOLDER
